version: 2.1
orbs:
  cypress: cypress-io/cypress@1

commands:
  configure-git:
    description: |
      Sets mandatory git config fields to allow creating and pushing of tags.
    steps:
      - run:
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
          name: git config

  git-merge-main:
    description: Merge main into stable
    steps:
      - run:
          command: |
            git checkout stable
            git merge main
            git push origin stable

  push-git-tag:
    description: Push git tag to your repository
    steps:
      - run:
          command: |
            TAG=$(cat package.json | jq -r '.version')
            git tag -a "v$TAG" -m "Release version $TAG"
            git push origin "v$TAG"
          name: Push git tag

jobs:
  update_stable_branch:
    description: Update the stable branch
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '94:b8:cc:b6:44:bf:93:61:92:2f:bf:1b:3e:93:88:ba'
      - configure-git
      - checkout
      - git-merge-main
      - push-git-tag

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:10001'
      - hold:
          type: approval
          requires:
            - cypress/run
      - update_stable_branch:
          name: deploy_to_production
          requires:
            - hold
          filters:
            branches:
              only: main
