version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  deploy:
    description: A job that deploys to netlify using the API.
    parameters:
      access_token:
        type: string
      site_id:
        type: string
    machine: true
    steps:
      - run:
          command: |
            curl -X POST -H "Authorization: Bearer << parameters.access_token >>" https://api.netlify.com/api/v1/sites/<< parameters.site_id >>/builds

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:10001'
      - deploy:
          name: deploy_to_staging
          access_token: $NETLIFY_BOT_ACCESS_TOKEN
          site_id: $STAGING_NETLIFY_SITE_ID
          requires:
            - cypress/run
          filters:
            branches:
              only: main
      - hold:
          type: approval
          requires:
            - deploy_to_staging
      - deploy:
          name: deploy_to_production
          access_token: $NETLIFY_BOT_ACCESS_TOKEN
          site_id: $PRODUCTION_NETLIFY_SITE_ID
          requires:
            - hold
          filters:
            branches:
              only: main
