version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1.6
  npm-publisher: uraway/npm-publisher@0.2.0

executors:
  cypress-node16:
    docker:
      - image: 'cypress/browsers:node16.5.0-chrome94-ff93'

commands:
  configure-git:
    description: |
      Sets mandatory git config fields to allow creating and pushing of tags.
    steps:
      - run:
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
          name: git config

  git-merge-main:
    description: Merge main into stable
    steps:
      - run:
          command: |
            git checkout stable
            git merge main
            git push origin stable

  rollbar-deploy:
    description: Logs the deploy action in Rollbar
    steps:
      - run:
          name: Deployment notification to Rollbar
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
              -F access_token=$ROLLBAR_ACCESS_TOKEN \
              -F environment=production \
              -F revision=$(awk -F\" '/"version":/ {print $4}' ~/project/package.json) \
              -F local_username=$CIRCLE_USERNAME

  rollbar-sourcemaps:
    description: Uploads sourcemaps to Rollbar
    steps:
      - run:
          name: Upload sourcemap to Rollbar
          command: |
            curl https://api.rollbar.com/api/1/sourcemap/ \
              -F access_token=$ROLLBAR_ACCESS_TOKEN \
              -F version=$(awk -F\" '/"version":/ {print $4}' ~/project/package.json) \
              -F minified_url=//assets.magicbell.io/magicbell.min.js \
              -F source_map=@/home/circleci/project/magicbell.min.js.map

jobs:
  update_stable_branch:
    description: Update the stable branch
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '94:b8:cc:b6:44:bf:93:61:92:2f:bf:1b:3e:93:88:ba'
      - configure-git
      - checkout
      - git-merge-main

  update_rollbar:
    description: Inform rollbar about the new version and register sourcemaps
    machine: true
    steps:
      - restore_cache:
          keys:
            - 'dist-{{ .Branch }}-{{ .Revision }}'
      - rollbar-deploy
      - rollbar-sourcemaps

workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress-node16
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:10001'
      - hold:
          type: approval
          requires:
            - cypress/run
          filters:
            branches:
              only: main
      - npm-publisher/publish-from-package-version:
          name: publish_to_npm
          requires:
            - hold
          filters:
            branches:
              only: main
          ssh-fingerprints: 94:b8:cc:b6:44:bf:93:61:92:2f:bf:1b:3e:93:88:ba
          pre-publish-steps:
            - run: yarn install
          post-publish-steps:
            - save_cache:
                key: 'dist-{{ .Branch }}-{{ .Revision }}'
                paths:
                  - dist
                  - package.json
          publish-token-variable: NPM_TOKEN
      - update_stable_branch:
          name: deploy_to_netlify
          requires:
            - hold
          filters:
            branches:
              only: main
      - update_rollbar:
          requires:
            - publish_to_npm
