version: 2.1
orbs:
  cypress: cypress-io/cypress@1

commands:
  git-merge-main:
    description: Merge main into stable
    steps:
      - run:
          command: |
            git pull origin main
            git checkout stable
            git merge main
            git push origin stable

  push-git-tag:
    description: Push git tag to your repository
    steps:
      - run:
          command: |
            TAG=$(cat package.json | jq -r '.version')
            git tag -a "v$TAG"
            git push origin "v$TAG"
          name: Push git tag

jobs:
  deploy:
    description: A job that deploys to netlify using the API.
    parameters:
      access_token:
        type: string
      site_id:
        type: string
    machine: true
    steps:
      - run:
          command: |
            curl -X POST -H "User-Agent: CircleCI" -H "Authorization: Bearer << parameters.access_token >>" -H "Content-Type: application/json" -d {} https://api.netlify.com/api/v1/sites/<< parameters.site_id >>/builds

  update_stable_branch:
    description: Update the stable branch
    machine: true
    steps:
      - git-merge-main
      - push-git-tag

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:10001'
      - deploy:
          name: deploy_to_staging
          access_token: $NETLIFY_BOT_ACCESS_TOKEN
          site_id: $STAGING_NETLIFY_SITE_ID
          requires:
            - cypress/run
          filters:
            branches:
              only: main
      - hold:
          type: approval
          requires:
            - deploy_to_staging
      - update_stable_branch:
          requires:
            - hold
          filters:
            branches:
              only: main
      - deploy:
          name: deploy_to_production
          access_token: $NETLIFY_BOT_ACCESS_TOKEN
          site_id: $PRODUCTION_NETLIFY_SITE_ID
          requires:
            - update_stable_branch
          filters:
            branches:
              only: main
