version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1.6
  npm-publisher: uraway/npm-publisher@0.2.0

executors:
  cypress-node16:
    docker:
      - image: 'cypress/browsers:node16.5.0-chrome94-ff93'

commands:
  configure-git:
    description: |
      Sets mandatory git config fields to allow creating and pushing of tags.
    steps:
      - run:
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
          name: git config

  git-merge-main:
    description: Merge main into stable
    steps:
      - run:
          command: |
            git checkout stable
            git merge main
            git push origin stable

jobs:
  update_stable_branch:
    description: Update the stable branch
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '94:b8:cc:b6:44:bf:93:61:92:2f:bf:1b:3e:93:88:ba'
      - configure-git
      - checkout
      - git-merge-main

workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress-node16
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:10001'
      - hold:
          type: approval
          requires:
            - cypress/run
          filters:
            branches:
              only: main
      - npm-publisher/publish-from-package-version:
          name: publish_to_npm
          requires:
            - hold
          filters:
            branches:
              only: main
          ssh-fingerprints: 94:b8:cc:b6:44:bf:93:61:92:2f:bf:1b:3e:93:88:ba
          pre-publish-steps:
            - run: yarn install
          publish-token-variable: NPM_TOKEN
      - update_stable_branch:
          name: deploy_to_netlify
          requires:
            - hold
          filters:
            branches:
              only: main
